version=0.1
[default.deploy.parameters]
stack_name = "xxxxxxxxxxxxx"
s3_bucket = "xxxxxxxxxxxxx"
s3_prefix = "xxxxxxxxxxxxx"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MyRoleARN=\"arn:aws:iam::123456789123:role/test-role\""
